name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: mcr.microsoft.com/playwright:v1.49.1-noble  # Use official Playwright Docker image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Playwright Tests in Docker
      run: |
        docker run \
          --rm \
          --shm-size=1gb \
          -v ${{ github.workspace }}:/work \
          -w /work/playwright-project \
          mcr.microsoft.com/playwright:v1.49.1-noble \
          /bin/bash -c "npm install && npx playwright install && npx playwright test"

    - name: Upload Playwright Test Report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-project/playwright-report